"""progression_engine_redesign

Revision ID: 40231fc08231
Revises: cb42ec727cf1
Create Date: 2026-06-03 10:40:26.165587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40231fc08231'
down_revision: Union[str, Sequence[str], None] = 'cb42ec727cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('formula_name', sa.String(), nullable=False),
    sa.Column('formula_code', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    with op.batch_alter_table('system_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_jobs_id'), ['id'], unique=False)

    op.create_table('category_progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('focus', 'health', 'discipline', 'mind', name='habitcategory'), nullable=False),
    sa.Column('category_xp', sa.Integer(), nullable=False),
    sa.Column('category_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uix_user_category_progression')
    )
    with op.batch_alter_table('category_progressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_progressions_id'), ['id'], unique=False)

    op.create_table('progression_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progression_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progression_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_progression_events_user_id'), ['user_id'], unique=False)

    op.create_table('score_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('old_xp', sa.Integer(), nullable=False),
    sa.Column('delta_xp', sa.Integer(), nullable=False),
    sa.Column('new_xp', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('score_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_milestones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_milestones_user_id'), ['user_id'], unique=False)

    op.create_table('habit_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_habit_id', sa.Integer(), nullable=False),
    sa.Column('child_habit_id', sa.Integer(), nullable=False),
    sa.Column('chain_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_habit_id', 'child_habit_id', name='uix_user_habit_chain')
    )
    with op.batch_alter_table('habit_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_dependencies_id'), ['id'], unique=False)

    op.create_table('habit_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('times_completed', sa.Integer(), nullable=False),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('mastery_xp', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'habit_id', name='uix_user_habit_mastery')
    )
    with op.batch_alter_table('habit_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_mastery_id'), ['id'], unique=False)

    op.create_table('habit_progression_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('habit_type', sa.String(), nullable=False),
    sa.Column('difficulty_coefficient', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'version', name='uix_habit_profile_version')
    )
    with op.batch_alter_table('habit_progression_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_progression_profiles_id'), ['id'], unique=False)

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scoring_version', sa.String(), server_default='v1', nullable=False))
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_snapshot_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('formula_snapshot_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quality_multiplier', sa.Float(), server_default='1.0', nullable=False))
        batch_op.add_column(sa.Column('consistency_multiplier', sa.Float(), server_default='1.0', nullable=False))
        batch_op.add_column(sa.Column('mastery_bonus', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_foreign_key('fk_daily_logs_profile_id', 'habit_progression_profiles', ['profile_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('base_score')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('plan_habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_period_minutes', sa.Integer(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('late_threshold_minutes', sa.Integer(), server_default='120', nullable=False))

    with op.batch_alter_table('user_plan_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('total_points')

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('energy_score', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('recovery_tokens', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('prestige_level', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rank', sa.String(), server_default='Beginner', nullable=False))
        batch_op.add_column(sa.Column('consistency_7d', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('consistency_30d', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('consistency_90d', sa.Float(), server_default='0.0', nullable=False))
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.INTEGER(), nullable=False))
        batch_op.drop_column('consistency_90d')
        batch_op.drop_column('consistency_30d')
        batch_op.drop_column('consistency_7d')
        batch_op.drop_column('rank')
        batch_op.drop_column('prestige_level')
        batch_op.drop_column('recovery_tokens')
        batch_op.drop_column('energy_score')
        batch_op.drop_column('total_xp')

    with op.batch_alter_table('user_plan_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.INTEGER(), nullable=False))
        batch_op.drop_column('total_xp')

    with op.batch_alter_table('plan_habits', schema=None) as batch_op:
        batch_op.drop_column('late_threshold_minutes')
        batch_op.drop_column('grace_period_minutes')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('base_score', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_logs_profile_id', type_='foreignkey')
        batch_op.drop_column('mastery_bonus')
        batch_op.drop_column('consistency_multiplier')
        batch_op.drop_column('quality_multiplier')
        batch_op.drop_column('formula_snapshot_json')
        batch_op.drop_column('profile_snapshot_json')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('scoring_version')

    with op.batch_alter_table('habit_progression_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_progression_profiles_id'))

    op.drop_table('habit_progression_profiles')
    with op.batch_alter_table('habit_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_mastery_id'))

    op.drop_table('habit_mastery')
    with op.batch_alter_table('habit_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_dependencies_id'))

    op.drop_table('habit_dependencies')
    with op.batch_alter_table('user_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_milestones_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_milestones_id'))

    op.drop_table('user_milestones')
    with op.batch_alter_table('score_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_score_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_score_events_date'))

    op.drop_table('score_events')
    with op.batch_alter_table('progression_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progression_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_progression_events_event_type'))

    op.drop_table('progression_events')
    with op.batch_alter_table('category_progressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_progressions_id'))

    op.drop_table('category_progressions')
    with op.batch_alter_table('system_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_jobs_id'))

    op.drop_table('system_jobs')
    op.drop_table('scoring_versions')
    # ### end Alembic commands ###
