"""postgresql_optimization_pass

Revision ID: bd825ef16990
Revises: 81f21cafabc3
Create Date: 2026-06-03 13:14:09.104724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd825ef16990'
down_revision: Union[str, Sequence[str], None] = '81f21cafabc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_score_change', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date')
    )
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.create_index('ix_category_progressions_user_category', 'category_progressions', ['user_id', 'category'], unique=False)
    op.add_column('daily_logs', sa.Column('category', sa.Enum('focus', 'health', 'discipline', 'mind', name='habitcategory'), nullable=False))
    op.add_column('daily_logs', sa.Column('awarded_points', sa.Integer(), nullable=False))
    op.alter_column('daily_logs', 'profile_snapshot_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="profile_snapshot_json::jsonb",
               existing_nullable=True)
    op.alter_column('daily_logs', 'formula_snapshot_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="formula_snapshot_json::jsonb",
               existing_nullable=True)
    op.create_index('ix_daily_logs_habit_id', 'daily_logs', ['habit_id'], unique=False)
    op.create_index('ix_daily_logs_plan_id', 'daily_logs', ['plan_id'], unique=False)
    op.create_index('ix_daily_logs_user_id_date', 'daily_logs', ['user_id', 'date'], unique=False)
    op.create_index('ix_daily_logs_user_id_status', 'daily_logs', ['user_id', 'status'], unique=False)
    op.create_index('ix_habit_dependencies_child', 'habit_dependencies', ['child_habit_id'], unique=False)
    op.create_index('ix_habit_dependencies_parent', 'habit_dependencies', ['parent_habit_id'], unique=False)
    op.create_index('ix_habit_mastery_mastery_level', 'habit_mastery', ['mastery_level'], unique=False)
    op.create_index('ix_habit_mastery_user_habit', 'habit_mastery', ['user_id', 'habit_id'], unique=False)
    op.add_column('habits', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.alter_column('habits', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('focus', 'health', 'discipline', 'mind', name='habitcategory'),
               postgresql_using="category::habitcategory",
               existing_nullable=False)
    op.drop_index(op.f('ix_habits_name'), table_name='habits')
    op.create_index(op.f('ix_habits_name'), 'habits', ['name'], unique=False)
    op.create_unique_constraint('uix_habit_name_creator', 'habits', ['name', 'created_by'])
    op.create_foreign_key('fk_habits_created_by', 'habits', 'users', ['created_by'], ['id'])
    op.alter_column('plans', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('progression_events', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="payload::jsonb",
               existing_nullable=False)
    op.create_index('ix_progression_events_created_at', 'progression_events', ['created_at'], unique=False)
    op.alter_column('score_events', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="metadata_json::jsonb",
               existing_nullable=True)
    op.create_index('ix_score_events_created_at', 'score_events', ['created_at'], unique=False)
    op.create_index('ix_score_events_event_type', 'score_events', ['event_type'], unique=False)
    op.create_index('ix_score_events_user_id_date', 'score_events', ['user_id', 'date'], unique=False)
    op.alter_column('scoring_versions', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using="parameters::jsonb",
               existing_nullable=False)
    op.add_column('user_plans', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index('ix_user_plans_plan_id', 'user_plans', ['plan_id'], unique=False)
    op.create_index('ix_user_plans_user_active', 'user_plans', ['user_id', 'active'], unique=False)
    op.create_index('uix_one_active_plan', 'user_plans', ['user_id'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_index(op.f('ix_user_stats_lifetime_xp'), 'user_stats', ['lifetime_xp'], unique=False)
    op.create_index(op.f('ix_user_stats_rank'), 'user_stats', ['rank'], unique=False)
    op.create_index(op.f('ix_user_stats_total_xp'), 'user_stats', ['total_xp'], unique=False)
    
    # Manually added CheckConstraints
    op.create_check_constraint("check_recovery_tokens_min", "user_stats", sa.text("recovery_tokens >= 0"))
    op.create_check_constraint("check_recovery_tokens_max", "user_stats", sa.text("recovery_tokens <= 3"))
    op.create_check_constraint("check_energy_score_min", "user_stats", sa.text("energy_score >= 0"))
    op.create_check_constraint("check_energy_score_max", "user_stats", sa.text("energy_score <= 100"))
    op.create_check_constraint("check_consistency_7d_min", "user_stats", sa.text("consistency_7d >= 0.0"))
    op.create_check_constraint("check_consistency_7d_max", "user_stats", sa.text("consistency_7d <= 1.0"))
    op.create_check_constraint("check_consistency_30d_min", "user_stats", sa.text("consistency_30d >= 0.0"))
    op.create_check_constraint("check_consistency_30d_max", "user_stats", sa.text("consistency_30d <= 1.0"))
    op.create_check_constraint("check_consistency_90d_min", "user_stats", sa.text("consistency_90d >= 0.0"))
    op.create_check_constraint("check_consistency_90d_max", "user_stats", sa.text("consistency_90d <= 1.0"))
    op.create_check_constraint("check_total_xp_min", "user_stats", sa.text("total_xp >= 0"))
    op.create_check_constraint("check_lifetime_xp_min", "user_stats", sa.text("lifetime_xp >= 0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_total_xp'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_rank'), table_name='user_stats')
    op.drop_index(op.f('ix_user_stats_lifetime_xp'), table_name='user_stats')
    op.drop_index('uix_one_active_plan', table_name='user_plans', postgresql_where=sa.text('active = true'))
    op.drop_index('ix_user_plans_user_active', table_name='user_plans')
    op.drop_index('ix_user_plans_plan_id', table_name='user_plans')
    op.drop_column('user_plans', 'end_date')
    op.alter_column('scoring_versions', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="parameters::json",
               existing_nullable=False)
    op.drop_index('ix_score_events_user_id_date', table_name='score_events')
    op.drop_index('ix_score_events_event_type', table_name='score_events')
    op.drop_index('ix_score_events_created_at', table_name='score_events')
    op.alter_column('score_events', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="metadata_json::json",
               existing_nullable=True)
    op.drop_index('ix_progression_events_created_at', table_name='progression_events')
    op.alter_column('progression_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="payload::json",
               existing_nullable=False)
    op.alter_column('plans', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_habits_created_by', 'habits', type_='foreignkey')
    op.drop_constraint('uix_habit_name_creator', 'habits', type_='unique')
    op.drop_index(op.f('ix_habits_name'), table_name='habits')
    op.create_index(op.f('ix_habits_name'), 'habits', ['name'], unique=True)
    op.alter_column('habits', 'category',
               existing_type=sa.Enum('focus', 'health', 'discipline', 'mind', name='habitcategory'),
               type_=sa.VARCHAR(),
               postgresql_using="category::varchar",
               existing_nullable=False)
    op.drop_column('habits', 'is_public')
    op.drop_column('habits', 'created_by')
    op.drop_index('ix_habit_mastery_user_habit', table_name='habit_mastery')
    op.drop_index('ix_habit_mastery_mastery_level', table_name='habit_mastery')
    op.drop_index('ix_habit_dependencies_parent', table_name='habit_dependencies')
    op.drop_index('ix_habit_dependencies_child', table_name='habit_dependencies')
    op.drop_index('ix_daily_logs_user_id_status', table_name='daily_logs')
    op.drop_index('ix_daily_logs_user_id_date', table_name='daily_logs')
    op.drop_index('ix_daily_logs_plan_id', table_name='daily_logs')
    op.drop_index('ix_daily_logs_habit_id', table_name='daily_logs')
    op.alter_column('daily_logs', 'formula_snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="formula_snapshot_json::json",
               existing_nullable=True)
    op.alter_column('daily_logs', 'profile_snapshot_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="profile_snapshot_json::json",
               existing_nullable=True)
    op.drop_column('daily_logs', 'awarded_points')
    op.drop_column('daily_logs', 'category')
    op.drop_index('ix_category_progressions_user_category', table_name='category_progressions')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    
    # Manually dropped CheckConstraints
    op.drop_constraint("check_recovery_tokens_min", "user_stats", type_="check")
    op.drop_constraint("check_recovery_tokens_max", "user_stats", type_="check")
    op.drop_constraint("check_energy_score_min", "user_stats", type_="check")
    op.drop_constraint("check_energy_score_max", "user_stats", type_="check")
    op.drop_constraint("check_consistency_7d_min", "user_stats", type_="check")
    op.drop_constraint("check_consistency_7d_max", "user_stats", type_="check")
    op.drop_constraint("check_consistency_30d_min", "user_stats", type_="check")
    op.drop_constraint("check_consistency_30d_max", "user_stats", type_="check")
    op.drop_constraint("check_consistency_90d_min", "user_stats", type_="check")
    op.drop_constraint("check_consistency_90d_max", "user_stats", type_="check")
    op.drop_constraint("check_total_xp_min", "user_stats", type_="check")
    op.drop_constraint("check_lifetime_xp_min", "user_stats", type_="check")
    # ### end Alembic commands ###
