"""stabilization fixes v1

Revision ID: cb42ec727cf1
Revises: bc070cde0a98
Create Date: 2026-04-01 10:01:44.411972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb42ec727cf1'
down_revision: Union[str, Sequence[str], None] = 'bc070cde0a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_habit_date', ['user_id', 'habit_id', 'date'])
        batch_op.drop_column('snapshot_category')
        batch_op.drop_column('points_awarded')

    with op.batch_alter_table('plan_habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_column('time_window')

    with op.batch_alter_table('user_plan_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('discipline_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mind_points', sa.Integer(), nullable=False))

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('discipline_points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mind_points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('mind_points')
        batch_op.drop_column('discipline_points')
        batch_op.drop_column('health_points')
        batch_op.drop_column('focus_points')

    with op.batch_alter_table('user_plan_stats', schema=None) as batch_op:
        batch_op.drop_column('mind_points')
        batch_op.drop_column('discipline_points')
        batch_op.drop_column('health_points')
        batch_op.drop_column('focus_points')

    with op.batch_alter_table('plan_habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_window', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_awarded', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('snapshot_category', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uix_user_habit_date', type_='unique')

    # ### end Alembic commands ###
